### ISSUE TITLE
Discussion: Should we launch with parity poa or wait for cosmos?

### ISSUE THREAD

**Issue by lkngtn** [1Hive/flora#1]
We have a mostly working setup with Parity POA that was started as ETHBerlin. I am also still paying to run the network on Azure. 

We should make a decision on how to proceed soon, if we are not planning on launching using the Azure infrastructure I can shut it down. 

Going the cosmos route seems like it will be more secure and more interesting over the long term, but its also unclear how complex implementing the discount model will be, when ethermint will be ready, and whether blockscout will work with ethermint. 

Going the Parity POA route has much less technical unknowns, we are basically ready to go, but we may end up migrating to cosmos in the future.

**Comment by rperez89** [comment]
I think that we are not going to be able to take the flora project for at least 1.5 months, so if nobody is going to be able to play with it we should probably shut down so you are not wasting money. And if we decide to keep the server up we should create some kind of devops payment from our DAO to your address if you are the one that are paying for it.

**Comment by 0xGabi** [comment]
I believe we should keep experiment with what we have so far. The main issues I think are left to tackle are:

1. Deploy Aragon stack and expose gateways correctly
2. Finish the logic of the Discount Validator
3. Frame integration with the API to calculate discounts

The Ethereum mainnet network on the current state is becoming increasingly costly to use. So we can keep our efforts in deliver a usable Parity POA and near end of the year start putting efforts to move to cosmos.

**Comment by lkngtn** [comment]
> The Ethereum mainnet network on the current state is becoming increasingly costly to use. So we can keep our efforts in deliver a usable Parity POA and near end of the year start putting efforts to move to cosmos. 

Strongly agree with this, it's actually fairly urgent I think to have another target and since I know that cosmos has a way to create a genesis state it may not even be a terrible migration. 

> I believe we should keep experiment with what we have so far. The main issues I think are left to tackle are:

Would also add, deploying blockscout, and token bridges.

Also onboarding a few additional validators (we could probably get A1 to run one fairly easily, and hopefully also get them to add Flora as a supported network on app.aragon.org)

**Comment by yeqbfgxjiq** [comment]
Been thinking about [how to actually use SourceCred](https://discourse.sourcecred.io/t/utopia-vs-dystopia/223) and having a fast/cheap sidechain would be really helpful. This is a natural fit for a PoA style chain because SourceCred itself is built on a "trust, but veirfy" model which is essentially how PoA works. [CreDAO](https://github.com/1hive/credao) and other SourceCred instances could be one of the first users of Flora, and... if SourceCred is popular (which I think it will be) this could be a win/win for all parties involved. SourceCred would have a more user friendly environment/experience to offer users, and we would have users lol
- Also, if we can easily migrate to Cosmos or any other EVM compatible sidechain in the future then that's even better

**Comment by onbjerg** [comment]
Closed as Flora is now configuration/notes on setting up an Arachain validator
